### ISSUE TITLE
remove resume download button & and fix writing spelling / typography contact me here

### ISSUE THREAD

**Issue by adydetra** [Katyusha47/portofolio-sy#1]
Remove all resume download buttons, except on the main page. 

And fix contact page, example:

![example](https://github.com/Katyusha47/portofolio-sy/assets/108399634/ea1d1b1b-9fd7-44ed-8cb4-f6228f6c2ee4)

**Comment by Katyusha47** [comment]
seeep 

ingfo diterima

**Comment by devdewa** [comment]
pilih diatara 4 itu, rekomendasi 2 & 1

**Comment by adydetra** [comment]
pilih diantara 4 itu, rekomendasi 2 & 1

**Comment by Katyusha47** [comment]
done cuma yg contact nanti paling
